### ISSUE TITLE
Multiple ports of Hyde theme

### ISSUE THREAD

**Issue by Kkloss** [spf13/hyde#31]
I was looking through the different themes available for Hugo and settled on using Hyde but I see that there are multiple ports. There is this and @zyro's [hyde-x](https://github.com/zyro/hyde-x) and @enten's [hyde-y](https://github.com/enten/hyde-y). Now, I am all for variety but looking at the differences between each project, I am not seeing any major differences between the three. At least none that could not be implemented behind config flags.

Is there any reason why the difference projects can't be combined?

**Comment by digitalcraftsman** [comment]
Both hyde-x and hyde-y are independent forks of this theme. I guess hyde-x was because it's maintainer wanted a custom and more flexible solution. Maybe the same applies to hyde-y.

Reach out to the maintainers of both projects.

**Comment by digitalcraftsman** [comment]
Closing this as stall.
