### ISSUE TITLE
any way to make the index as Single page?

### ISSUE THREAD

**Issue by hloeffler** [spf13/hyde#38]
Hello,
thanks for your theme,
i'm new to hugoand wanted to create a simple site,
but i want a static "/" (index.md) instead of a list,
but it seems this is not possible with this theme
any easy way to change it?

see also:
https://discuss.gohugo.io/t/render-index-md-as-single/5533

**Comment by z0li** [comment]
@hloeffler: as I see you got some help on the Hugo support forum back in 2017. Do you think the issue can be closed?

**Comment by hloeffler** [comment]
sure, thanks
