### ISSUE TITLE
sidebar flickers on Safari iPad

### ISSUE THREAD

**Issue by kevinburke** [spf13/hyde#4]
See debate here, need to patch/update the css file, probably

https://github.com/poole/poole/issues/7

**Comment by egonelbre** [comment]
@spf13 btw. this was (probably, didn't verify) fixed by 6d6546011f2d1aa172241124ff3de547b15b30bf.

**Comment by digitalcraftsman** [comment]
@kevinburke Is this issue still present? I can't confirm this, since I don't have a testing device.

**Comment by digitalcraftsman** [comment]
Since this issue inactive since a long time I'll close it.
