### ISSUE TITLE
Partials head.html Needs CSS Type Attribute

### ISSUE THREAD

**Issue by MCDELTAT** [spf13/hyde#49]
With just the default installation I'm running into an issue in Chrome 65 where it reports that it won't load the CSS Pages because the MIME type defaults to "text/plain" and strict type checking is turned on by default in 65. To fix this I simply added the attribute 'type="text/css"' to the individual tags in head.html.

I've never worked extensively with submodules before so I'm not sure on how to submit a pull request on it, but I would gladly do so.

**Comment by bep** [comment]
In my head this is a problem with your web server and not Hugo, but It doesn't hurt, so I'll add it.
