### ISSUE TITLE
 mobile support?

### ISSUE THREAD

**Issue by v01d** [spf13/hyde#50]
When opening on chrome on my android device, a very rudimentary version of the site appears.

**Comment by z0li** [comment]
@v01d: could you be a bit more specific. Mobile support works fine for me on my Android phone.

Is it possible that you tested with `hugo serve` without specifying the correct `--baseURL` so the stylesheets and other assets were not downloaded properly?

**Comment by v01d** [comment]
Sorry, this was over a year ago. Don't even remember what was the issue.
