### ISSUE TITLE
Theme does not load on Netlify

### ISSUE THREAD

**Issue by rsyncOSX** [spf13/hyde#79]
Hi. I tried to change my theme from `ananke` to `hyde` on this docs : https://rsyncosx.netlify.app/. It loads perfectly on my Mac utilizing hugo server -D, but it does not load properly when building the docs on Netlify. I am not a Javascript developer, and I dont know what is missing in theme regarding Netlify. Switching back to theme ananke builds OK on Netlify.. I would prefer utilizing the `hyde`theme, seems as a better theme for docs..

**Comment by bep** [comment]
I'm totally guessing here -- but I suspect that Hyde is a little more dependent that the `baseURL` is set correctly.

**Comment by rsyncOSX** [comment]
Maybe, but the hyde theme builds OK on my Mac but not on Netlify.. I can try to build a new site with hyde theme and see how it goes..

**Comment by bep** [comment]
Yes, but locally it defaults to localhost and it just works. Netlify has its own URL. Try https://discourse.gohugo.io/ for questions.

**Comment by iroQuai** [comment]
For me it was the /  at the end of the "https://zyx.netlify.app/" which did the trick. Logical for some maybe, but took me a while. Posting here for later reference ;)
