### ISSUE TITLE
Not sure where to ask this, but how do I hide contents from my homepage that aren't in the /posts/ folder?

### ISSUE THREAD

**Issue by Tetizera** [spf13/hyde#84]
I tried finding a solution to this "problem" I have, but they are related to other themes, so I'm not exactly sure which file I should modify so that only /posts/ content is shown in the homepage.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
