### ISSUE TITLE
Fix `v.1.3.0` release

### ISSUE THREAD

**Issue by DazWilkin** [spf13/hyde#92]
The [`v.1.3.0`](https://github.com/spf13/hyde/releases/tag/v.1.3.0) tag|release has a period (`.`) between the `v` and `1`.

This requires `hugo mod get github.com/spf13/hyde@v.1.3.0` which is an invalid version and which unexpectedly (!) causes:

```bash
hugo mod get github.com/spf13/hyde@v.1.3.0
```
```console
go: downloading github.com/spf13/hyde v1.2.1-0.20240927070138-ad521afb8df1
go: upgraded github.com/spf13/hyde v1.2.0 => v1.2.1-0.20240927070138-ad521afb8df1
```

**Comment by bep** [comment]
See https://github.com/spf13/hyde/releases/tag/v1.3.0
